### ISSUE TITLE
Have 'node_deb.start_command' default to 'scripts.start'

### ISSUE THREAD

**Issue by ehartsuyker** [ehartsuyker/node-deb#13]
Suggestion from a coworker. Need to see if it makes sense.
@jeffhiltz, can you elaborate?

**Comment by jeffhiltz** [comment]
```scripts.start``` is indeed the default spot to put a start script for a Node.js package.  If that script isn't defined but there is a ```server.js``` file in the root of the package then ```scripts.start``` takes on the default value of ```node server.js```.

The start script is typically called by running ```npm start```.

Details here:

https://docs.npmjs.com/misc/scripts

**Comment by ehartsuyker** [comment]
Fixed by 5575ce0
