### ISSUE TITLE
Package generation is slow

### ISSUE THREAD

**Issue by theomega** [ehartsuyker/node-deb#14]
The package generation is very slow. The performance bottleneck is the loop which copies the files at
https://github.com/ehartsuyker/node-deb/blob/develop/node-deb#L451

For every file it spawns a new dirname process which takes a long time if you have 10k js files in your modules.

I don't understand why no `cp -Rv` is used here....

**Comment by ehartsuyker** [comment]
Fixed by c753ea15870b5e5bba6d23fe35427082b792fd29
