### ISSUE TITLE
Use `npm install --production` to install only dependencies

### ISSUE THREAD

**Issue by theomega** [ehartsuyker/node-deb#15]
Per default, `npm install` also installs the devDependencies. If you don't want to have these dependencies, you need to add the `--production` switch. 

The [documentation][1] explains this switch:

> By default, npm install will install all modules listed as dependencies in package.json.
> 
> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will    not install modules listed in devDependencies.

For the differences between the dependencies and the dev dependencies see the [explanation of package.json][2]:

> **dependencies**
> Please do not put test harnesses or transpilers in your dependencies object. See devDependencies, below.

> **devDependencies**
> If someone is planning on downloading and using your module in their program, then they probably don't want or need to download and build the external test or documentation framework that you use.
>In this case, it's best to map these additional items in a devDependencies object.
> These things will be installed when doing npm link or npm install from the root of a package, and can be managed like any other npm configuration param. See npm-config for more on the topic.
> For build steps that are not platform-specific, such as compiling CoffeeScript or other languages to JavaScript, use the prepublish script to do this, and make the required package a devDependency.

   [1]: https://docs.npmjs.com/cli/install
   [2]: https://docs.npmjs.com/files/package.json#devdependencies

**Comment by ehartsuyker** [comment]
@theomega Ha. Thanks. Not actually knowing anything about node/npm is biting my ass a bit. Expect a fix soon.

**Comment by ehartsuyker** [comment]
Fixed with 9dade955e422cbf5c3204d85db41751d847b45ca
